version: '3.3'

services:
   postgresql:
      image: postgis/postgis:14-3.2-alpine
      volumes:
        - ./deps/postgresql/data:/var/lib/postgresql/data
        - ./data:/data
        - ./imposm:/imposm
      ports:
        - "25433:5432"
      environment:
         - POSTGRES_USER=docker
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=gis
      restart: on-failure

   gdal:
      image: osgeo/gdal:ubuntu-small-3.4.2
      user: ${UID_GID}
      volumes:
        - ./data:/data

   trainer:
      build:
        context: .
        dockerfile: Dockerfile
      user: ${UID_GID}
      volumes:
        - ./data:/data
        - .:/app

   imposm:
      build:
        context: imposm
        dockerfile: Dockerfile
      image: imposm:latest
      volumes:
        - ./temp:/temp
        - ./temp:/go/bin/temp
        - ./imposm:/app/imposm
      user: ${UID_GID}
      depends_on:
        - postgresql
